version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.4
  node: circleci/node@4.1.0
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - node/install
      - checkout
      - eb/setup
      - aws-cli/setup
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Front-End test
          command: |
            npm run frontend:test
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Deploy BackEnd App
          command: |
            npm run backend:deploy
      - run:
          name: Deploy FrontEnd App
          command: |
            npm run frontend:deploy
workflows:
  branches:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main